### ISSUE TITLE
SOFT2 numerical distribution function

### ISSUE THREAD

**Issue by jmcclena** [hoppe93/SOFT2#1]
Hi Mathias,

Do you have an example numerical distribution function for running SOFT2? I tried to create one for testing purposes with the following script, but I'm messing up somewhere since SOFT2 is returning zeros for my image.

```
ngrid = 51
r = np.zeros([1,51])
r[0,:] = np.linspace(0,2.6,ngrid)
xi = np.zeros([1,51])
xi[0,:] = np.linspace(-1,1,ngrid)
p = np.zeros([1,51])
p[0,:] = np.linspace(0,5e7,ngrid)

veldim = len(xi[0,:])*len(p[0,:])
fvel = np.reshape(f, (1, veldim))

F = np.zeros((len(r[0,:]), veldim))
for i in range(0,len(r)):
    F[i,:] = ones(veldim)

desc = 'Sample numerical dist'
name = 'samp'
punits = 'ev'

import h5py
dist = h5py.File('dist_sample.h5', 'w')
dist.create_dataset('description',data=desc )
dist.create_dataset('f', data=F)
dist.create_dataset('name', data=name)
dist.create_dataset('p', data=p)
dist.create_dataset('punits', data=punits)
dist.create_dataset('r', data=r)
dist.create_dataset('xi', data=xi)
dist.close()
```

**Comment by hoppe93** [comment]
Hi Joseph! The issue seems to be in the for loop. For me, ``len(r)`` returns 1, since ``r`` is actually a 1-by-51 matrix, meaning that F is zero everywhere except for at r=0 (which has a vanishing Jacobian and therefore doesn't contribute anyway). When I replace ``len(r)`` with ``r.size`` I get a 51-by-(51^2) matrix of ones which should give some more radiation.

**Comment by jmcclena** [comment]
Oh jeez, I'm a dummy. Thanks!
